title: Fichier

columns:
  main:
    width: 1/2
    sections:
      content:
        type: fields
        fields:
          caption:
            label: Légende
            type: markdown
            size: medium
  sidebar:          
    width: 1/2
    sections:
      meta:
        type: fields
        fields:
          alt:
            label: Alternative Text
            type: text