title: Page par défaut

columns:
  sidebar:
    width: 1/3
    sections:
      files:
        type: files
        label: Fichiers / Images
      fields: 
        type: fields
        fields: 
          description: 
            label: Description pour les moteurs de recherche
            type: textarea
          imgSocial: 
            label: Image pour les réseaux sociaux
            type: files
            query: page.images
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            label: Texte
            type:  markdown