title: Page par défaut

columns:
  sidebar:
    width: 1/3
    sections:
      files:
        type: files
        label: Fichiers / Images
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            label: Texte
            type:  markdown